# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Setup pnpm
        # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
      uses: pnpm/action-setup@v2.2.4
      with:
        # Version of pnpm to install
        version: 8.3.1
        # Where to store pnpm files
        # dest: # optional, default is ~/setup-pnpm
        # If specified, run `pnpm install`
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store

    - name: Install
      run: pnpm i

    - name: Run linter
      run: pnpm lint

    - name: Build ui
      run: pnpm build --filter=./packages/*

    - name: Run typecheck
      run: pnpm typecheck

    - name: Run coverage
      run: pnpm coverage

    - name: 'Report UI Coverage'
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        title: "packages/ui"
        lcov-file: ./packages/ui/coverage/lcov.info
        lcov-base: ./packages/ui
        github-token: ${{secrets.COVERAGE_TOKEN}}
        delete-old-comments: true

    - name: 'Report coco-live Coverage'
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        title: "apps/coco-live"
        lcov-base: ./apps/coco-live
        lcov-file: ./apps/coco-live/coverage/lcov.info
        github-token: ${{secrets.COVERAGE_TOKEN}}
        delete-old-comments: true




